# readthedocs.yml

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages: 
    - cmake
    - make
    - libeigen3-dev
    - libboost-all-dev
  jobs:
    post_install:
      - wget https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/openbabel-3.1.1-source.tar.bz2 
      - tar xjf openbabel-3.1.1-source.tar.bz2 
      - mkdir build
      - cd build
      - cmake ../openbabel-3.1.1
      - make -j4
      - sudo make install

python:
  version: 3.8
  install:
    - method: pip
      path: .

conda:
  environment: docs/requirements.yaml
